### ISSUE TITLE
java.lang.StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by abunayem** [nabil6391/qurantajweed#1]
java.lang.StringIndexOutOfBoundsException: length=85; index=85
        at java.lang.String.charAt(Native Method)
        at com.example.app.tajweed.QuranArabicUtils.getEnd(QuranArabicUtils.java:226)
        at com.example.app.tajweed.QuranArabicUtils.getTajweed(QuranArabicUtils.java:179)

**Comment by nabil6391** [comment]
Can you let me know what is the text that is being used?

**Comment by abunayem** [comment]
I have tested it with various ayat from the Quran. it crashes sometimes not all time in baqara ayat no 6. al-Imran ayat no 3 and so on. also color not applying properly all-time in specific ayat. like last letter (dal) of sura ikhlas ayat no 1, 2, 4 not colorings. text tested from tanzil.com, quran.ksu.edu.sa/ayat and shamela.ws
